[package]
name = "libsphinx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halite-sys = "0.1.3"
hex = "0.4.3"
thiserror = "1.0.38"
